### ISSUE TITLE
Document the update process for demo servers when a new version is release

### ISSUE THREAD

**Issue by silentninja** [mathesar-foundation/mathesar-wiki#104]
## Problem

When a new Mathesar version is released we need to update the demo server and a few other internal servers. The process to update these servers is not documented in our wiki.

**Comment by seancolsen** [comment]
@mathemancer I'm re-assigning this to you no that Mukesh won't be working on it anymore. It still seems like it would be a useful thing to do.

**Comment by kgodey** [comment]
Closing since we have this page: https://wiki.mathesar.org/engineering/server-update-process/
