### ISSUE TITLE
Document front end coding standards for imports

### ISSUE THREAD

**Issue by seancolsen** [mathesar-foundation/mathesar-wiki#23]
- Relative vs absolute
- When to use aliases
- `@mathesar-component-library` vs `@mathesar-component-library-dir`
- When to add new code to a `index.ts`

**Comment by seancolsen** [comment]
Here's a start at some content

> ## Imports
> 
> The following rubric helps keep our imports clean and easy to refactor:
> 
> - When possible, import symbols from a high-level `index.ts` file instead of from more deeply nested files.
> 
>     - Good ✅
> 
>         ```ts
>         import { getTabularContent } from '@mathesar/stores/table-data';
>         ```
> 
>     - Bad ❌
> 
>         ```ts
>         import { getTabularContent } from '@mathesar/stores/table-data/manager';
>         ```

I think the rest of the content can probably follow the same pattern. 

I'm having trouble writing the rest of it though because I only have a vague sense of the rules. This has come up many times in review of my PRs, so it would be helpful for _me_ to have some documentation like this to follow. 

@pavish would you be up for finishing this content?

**Comment by pavish** [comment]
@seancolsen Yes, I'll come up with the content.

**Comment by seancolsen** [comment]
I'm closing this since it's very old.
